// Test generated by RoostGPT for test testReactJan10 using AI Type Open AI and AI Model gpt-4-1106-preview


// Import required libraries and the reducer
import reducer from '../../../src/reducers/charge';
import { SET_CHARGES_LIST, SET_ONE_CHARGE } from '../../../src/constants/charge';

describe('charge reducer', () => {
  it('should return the initial state when no action is passed', () => {
    const initialState = {
      chargeList: [],
      oneCharge: []
    };
    expect(reducer(undefined, {})).toEqual(initialState);
  });

  it('should handle SET_CHARGES_LIST', () => {
    const initialState = {
      chargeList: [],
      oneCharge: []
    };
    const action = {
      type: SET_CHARGES_LIST,
      payload: ['charge1', 'charge2']
    };
    const expectedState = {
      chargeList: ['charge1', 'charge2'],
      oneCharge: []
    };
    expect(reducer(initialState, action)).toEqual(expectedState);
  });

  it('should handle SET_ONE_CHARGE', () => {
    const initialState = {
      chargeList: ['charge1', 'charge2'],
      oneCharge: []
    };
    const action = {
      type: SET_ONE_CHARGE,
      payload: ['charge3']
    };
    const expectedState = {
      chargeList: ['charge1', 'charge2'],
      oneCharge: ['charge3']
    };
    expect(reducer(initialState, action)).toEqual(expectedState);
  });
});

