// Test generated by RoostGPT for test testReactJan10 using AI Type Open AI and AI Model gpt-4-1106-preview


// Filename: __tests__/src/store/index.test.js

// Import dependencies
import { createStore, applyMiddleware } from 'redux';
import ReduxThunk from 'redux-thunk';
import rootReducer from '../../../src/reducers/index'; // Adjusted to correct relative path based on the test file location

describe('Redux store configuration', () => {
  it('should create a store with the root reducer and middleware applied', () => {
    const store = createStore(rootReducer, applyMiddleware(ReduxThunk));
    expect(store).toBeDefined();
    expect(store.getState()).toEqual(rootReducer(undefined, {}));
  });

  it('should fail to create a store without the root reducer', () => {
    // Here we are not providing the rootReducer on purpose for this test case.
    // In a real-world scenario, Redux would throw an error,
    // which you would usually handle differently.
    // This is just to demonstrate a negative test case.
    expect(() => createStore(undefined, applyMiddleware(ReduxThunk)))
      .toThrowError();
  });
});

