// Test generated by RoostGPT for test testReactJan10 using AI Type Open AI and AI Model gpt-4-1106-preview


import React from 'react';
import { render } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Route from '../../../src/components/Route/index.js'; // Corrected import path based on the test file location

describe('Route Component', () => {
  // Cleanup mock
  afterEach(() => {
    jest.restoreAllMocks();
  });

  test('renders Customer component by default', () => {
    window.history.pushState({}, 'Test', '/?component=customer');
    const { getByText } = render(<Route />);
    expect(getByText('Customer')).toBeInTheDocument();
  });
  
  test('renders Charge component when specified', () => {
    window.history.pushState({}, 'Test', '/?component=charge');
    const { getByText } = render(<Route />);
    expect(getByText('Charge')).toBeInTheDocument();
  });

  test('adds keydown event listener on mount', () => {
    const addListenerSpy = jest.spyOn(window, 'addEventListener');
    render(<Route />);
    expect(addListenerSpy).toHaveBeenCalledWith('keydown', expect.any(Function), true);
  });

  test('removes keydown event listener on unmount', () => {
    const removeListenerSpy = jest.spyOn(window, 'removeEventListener');
    const { unmount } = render(<Route />);
    unmount();
    expect(removeListenerSpy).toHaveBeenCalledWith('keydown', expect.any(Function), true);
  });

  // Add more tests if needed...
  
});

